import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import axiosInstance, { errorMessage } from "../../services/axiosInstance.js";
import { useDecision } from "../../components/DecisionProvider.jsx";
const timeLabel = (seconds) => `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;
function Attempt({ id }) {
  const decide = useDecision();
  const [attempt, setAttempt] = useState(null), [error, setError] = useState(""), [busy, setBusy] = useState(false), [failed, setFailed] = useState(null), [clock, setClock] = useState(0), [questionIndex, setQuestionIndex] = useState(0);
  const requests = useRef(new Set()), pending = useRef(false), anchor = useRef(null), timeoutRequested = useRef(false), latestRevision = useRef(-1);
  const request = useCallback(async (method, suffix = "", body) => {
    const controller = new AbortController(); requests.current.add(controller);
    try { const response = await axiosInstance({ method, url: `/assessment-attempts/${id}${suffix}`, data: body, signal: controller.signal }); return controller.signal.aborted ? null : response.data.data.attempt; }
    finally { requests.current.delete(controller); }
  }, [id]);
  const apply = useCallback((next) => { const revision = next.revision ?? 0; if (revision < latestRevision.current) return; latestRevision.current = revision; anchor.current = { server: Date.parse(next.serverNow), local: performance.now() }; setClock(performance.now()); setAttempt(next); }, []);
  const load = useCallback(async () => {
    try { const next = await request("get"); if (next) { apply(next); setError(""); } } catch (e) { if (e.code !== "ERR_CANCELED") { setError(errorMessage(e)); if ([401, 402, 403, 404, 410].includes(e.response?.status)) setAttempt(null); } }
  }, [request, apply]);
  useEffect(() => { load(); const refresh = setInterval(() => { if (!pending.current) load(); }, 15000), tick = setInterval(() => setClock(performance.now()), 1000); const activeRequests = requests.current; return () => { clearInterval(refresh); clearInterval(tick); activeRequests.forEach((c) => c.abort()); }; }, [load]);
  const perform = useCallback(async (suffix, body, method = "post") => {
    if (pending.current) return; pending.current = true; setBusy(true); setError("");
    try { const next = await request(method, suffix, body); if (next) { apply(next); setFailed(null); } }
    catch (e) { if (e.code !== "ERR_CANCELED") { setFailed({ suffix, body, method }); setError(errorMessage(e)); if (e.response?.status === 409) await load(); else if ([401, 402, 403, 404, 410].includes(e.response?.status)) setAttempt(null); } throw e; }
    finally { pending.current = false; setBusy(false); }
  }, [request, apply, load]);
  const remaining = attempt?.deadline && anchor.current ? Math.max(0, Math.ceil((Date.parse(attempt.deadline) - anchor.current.server - (clock - anchor.current.local)) / 1000)) : null;
  useEffect(() => { if (remaining === 0 && attempt?.status === "active" && !busy && !timeoutRequested.current) { timeoutRequested.current = true; perform("/submit", {}).catch(() => {}); } }, [remaining, attempt?.status, busy, perform]);
  const submit = async () => {
    const unanswered = attempt.answers.filter((answer) => answer === null).length;
    await decide({ title: "Submit your attempt?", body: `${unanswered} unanswered ${unanswered === 1 ? "question" : "questions"} will earn 0 points. Your saved answers will be scored, and this attempt will close.`, confirmLabel: "Submit attempt", onConfirm: () => perform("/submit", {}) });
  };
  const active = attempt?.status === "active", q = attempt?.questions[questionIndex];
  return <section><Link className="text-sm text-primary-700 underline dark:text-primary-300" to={attempt ? `/courses/${attempt.courseId}/assessments` : "/dashboard"}>← {attempt ? "Course assessments" : "Dashboard"}</Link>
    {error && <div className="card mt-5" role="alert"><p className="text-red-700 dark:text-red-300">{error}</p><div className="mt-4 flex flex-wrap gap-3">{failed && active && <button className="btn-secondary" disabled={busy} onClick={() => perform(failed.suffix, failed.body, failed.method).catch(() => {})}>Retry {failed.suffix === "/submit" ? "submission" : "answer"}</button>}<button className="btn-secondary" disabled={busy} onClick={load}>Reload attempt</button></div></div>}
    {!attempt && !error && <p role="status" className="mt-6">Loading your attempt…</p>}
    {attempt && <><header className="card mt-5"><p className="eyebrow">{active ? "Ek sawaal, ek step" : "Apni practice dekhein"} · Version {attempt.version}</p><h1 className="mt-3 break-words text-3xl font-semibold">{attempt.title}</h1>{active ? <><p className="mt-3 text-sm leading-7 text-muted">Choose one answer per question. Wait for “Answer saved” before leaving. Saved answers survive refresh; the server timer continues while you are away. Correct: +1. Incorrect or unanswered: 0.</p><p className="mt-4 font-semibold" role="timer" aria-live="off">{remaining === null ? "Untimed quiz" : `Time remaining: ${timeLabel(remaining)}`}</p>{remaining !== null && remaining <= 60 && <p className="mt-2 text-sm" role="status">{remaining === 0 ? "Time has ended. Retrieving your result…" : "Less than one minute remains."}</p>}<p role="status" className="mt-3 text-sm text-muted">{busy ? "Saving…" : failed ? "A request needs retry. Only saved answers count." : attempt.answers.some((answer) => answer !== null) ? "Answer saved" : "No answers saved yet"} · {attempt.answers.filter((v) => v !== null).length}/{attempt.questions.length} answered</p></> : <><p className="mt-4 text-2xl font-semibold">{attempt.result.correct}/{attempt.result.total} correct · {attempt.result.percentage}%</p><p className="mt-3 text-sm leading-7 text-muted">{attempt.status === "timed_out" ? "Time ended. Your saved answers were scored." : "Attempt submitted."} {attempt.result.total - attempt.result.answered} unanswered. This result reflects this authored question version.</p></>}</header>
      {active && q ? <section className="card mt-6 min-w-0"><fieldset disabled={busy || remaining === 0} className="min-w-0"><legend className="mb-5 break-words text-xl font-semibold">Question {questionIndex + 1} of {attempt.questions.length}: {q.prompt}</legend>{q.topic && <p className="mb-4 text-sm text-muted">Topic: {q.topic}</p>}<div className="space-y-3">{q.options.map((option, i) => <label className="flex min-h-12 cursor-pointer items-start gap-3 rounded-xl border border-line p-4 text-sm leading-7" key={i}><input className="mt-1.5 h-5 w-5 shrink-0 accent-primary-600" type="radio" name={`question-${questionIndex}`} checked={attempt.answers[questionIndex] === i} onChange={() => perform("/answers", { questionIndex, optionIndex: i }, "put").catch(() => {})} /><span className="min-w-0 break-words">{option}</span></label>)}</div><button className="btn-secondary mt-4" disabled={attempt.answers[questionIndex] === null} onClick={() => perform("/answers", { questionIndex, optionIndex: null }, "put").catch(() => {})}>Clear answer</button></fieldset><nav className="mt-5" aria-label="Jump to a question"><p className="text-sm font-semibold">Jump to a question</p><div className="mt-3 flex flex-wrap gap-2">{attempt.questions.map((_, index) => <button key={index} className="btn-secondary min-w-11 !px-3" aria-label={`Question ${index + 1}, ${attempt.answers[index] === null ? "unanswered" : "answered"}`} aria-current={index === questionIndex ? "step" : undefined} disabled={busy} onClick={() => setQuestionIndex(index)}>{index + 1}{attempt.answers[index] !== null ? " ✓" : ""}</button>)}</div></nav><nav className="mt-5 flex flex-wrap gap-3" aria-label="Question navigation"><button className="btn-secondary" disabled={busy || questionIndex === 0} onClick={() => setQuestionIndex(questionIndex - 1)}>Previous question</button><button className="btn-secondary" disabled={busy || questionIndex + 1 >= attempt.questions.length} onClick={() => setQuestionIndex(questionIndex + 1)}>Next question</button></nav><button className="btn-primary mt-6" disabled={busy || remaining === 0} onClick={submit}>Submit attempt</button></section> : !active && <section className="mt-6 space-y-5" aria-label="Result explanations">{attempt.questions.map((question, i) => <article className="card min-w-0" key={i}><h2 className="break-words text-xl font-semibold">Question {i + 1}: {question.prompt}</h2><p className="mt-4 break-words text-sm leading-7">Your answer: {attempt.review[i].selectedIndex === null ? "Unanswered" : question.options[attempt.review[i].selectedIndex]}</p><p className="mt-2 break-words text-sm font-semibold leading-7">Correct answer: {question.options[attempt.review[i].correctIndex]}</p><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-7 text-muted">{attempt.review[i].explanation}</p>{question.topic && <p className="mt-3 break-words text-sm text-muted">Topic: {question.topic}</p>}</article>)}</section>}
    </>}
  </section>;
}
export default function AssessmentAttemptPage() { const { id } = useParams(); return <Attempt key={id} id={id} />; }
