import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import axiosInstance, { errorMessage } from "../../services/axiosInstance.js";
import { useDecision } from "../../components/DecisionProvider.jsx";
import WorkspaceIntro from "../../components/WorkspaceIntro.jsx";
function CourseAssessments({ id }) {
  const navigate = useNavigate(), decide = useDecision();
  const [data, setData] = useState(null), [error, setError] = useState(""), [page, setPage] = useState(1);
  const load = useCallback(async (signal) => {
    try { const [course, available, history] = await Promise.all([axiosInstance.get(`/courses/${id}`, { signal }), axiosInstance.get(`/courses/${id}/assessments`, { signal }), axiosInstance.get(`/courses/${id}/assessment-attempts`, { params: { page }, signal })]); if (signal?.aborted) return; setData({ course: course.data.data.course, chapters: course.data.data.modules, assessments: available.data.data.assessments, history: history.data.data }); setError(""); } catch (e) { if (e.code !== "ERR_CANCELED") { setData(null); setError(errorMessage(e)); } }
  }, [id, page]);
  useEffect(() => { const controller = new AbortController(); setData(null); setError(""); load(controller.signal); return () => controller.abort(); }, [load]);
  const start = async (a) => {
    let attemptId;
    if (await decide({ title: `Start ${a.kind === "mock" ? "this mock test" : "this quiz"}?`, body: `${a.questionCount} questions. ${a.durationMinutes ? `The ${a.durationMinutes}-minute timer starts on the server now and continues if you leave or refresh.` : "This quiz is untimed."} ${a.feedbackMode === "after_answer" ? "New attempts reveal the correct option after each saved answer. Your first saved choice is final. Resumed attempts keep their original feedback rules. " : ""}Each correct answer earns 1 point. Incorrect or unanswered questions earn 0. Saved answers are retained if you leave.`, confirmLabel: "Start or resume", onConfirm: async () => { attemptId = (await axiosInstance.post(`/assessments/${a.id}/attempts`, {})).data.data.attempt.id; } })) navigate(`/assessment-attempts/${attemptId}`);
  };
  return <section><Link className="text-sm text-primary-700 underline dark:text-primary-300" to={`/courses/${id}`}>← Course</Link><div className="mt-5"><WorkspaceIntro eyebrow="Chalo, practice karein" title="Quizzes and mock tests">{data?.course.title || "Your authored course assessments"}</WorkspaceIntro></div>
    {error && <div className="card mt-5" role="alert"><p className="text-red-700 dark:text-red-300">{error}</p><button className="btn-secondary mt-4" onClick={() => load()}>Retry assessments</button></div>}
    {!data && !error && <p className="mt-5" role="status">Loading assessments…</p>}
    {data && <><p className="mt-5 text-sm leading-7 text-muted">Practice scores reflect your answers to these instructor-authored questions. Lesson completion is tracked separately.</p><p className="mt-3 text-sm leading-7 text-muted">A mock-test timer continues if you refresh or leave. Resume saved answers from the same account. Correct answers earn 1 point; incorrect or unanswered questions earn 0.</p>{["mock", "quiz"].map((kind) => <section className="mt-7" key={kind}><h2 className="text-2xl font-semibold">{kind === "mock" ? "Course mock tests" : "Chapter quizzes"}</h2><div className="mt-4 grid gap-5 md:grid-cols-2">{data.assessments.filter((a) => a.kind === kind).map((a) => <article className="card min-w-0" key={a.id}><p className="eyebrow">{a.kind === "mock" ? "Timed course mock test" : data.chapters.find((m) => m._id === a.moduleId)?.title || "Chapter quiz"}</p><h3 className="mt-3 break-words text-xl font-semibold">{a.title}</h3><p className="mt-3 text-sm text-muted">{a.questionCount} questions · {a.durationMinutes ? `${a.durationMinutes} minutes` : "Untimed"}</p><button className="btn-primary mt-5" onClick={() => start(a)}>Start or resume {a.kind === "mock" ? "mock test" : "quiz"}</button></article>)}</div>{!data.assessments.some((a) => a.kind === kind) && <p className="card mt-4">{kind === "mock" ? "Your instructor has not published a mock test for this course yet." : "Your instructor has not published a chapter quiz for this course yet."}</p>}</section>)}
      <section className="card mt-7"><h2 className="text-xl font-semibold">Topics to practise</h2><p className="mt-3 text-sm leading-7 text-muted">Author-tagged topics below 70% correct across your latest {data.history.summaryWindow} submitted attempts (up to 100). Untagged questions are excluded.</p>{data.history.weakTopics.length ? <ul className="mt-4 space-y-3">{data.history.weakTopics.map((t) => <li className="flex flex-wrap justify-between gap-2 rounded-xl bg-soft p-4" key={t.topic}><span className="min-w-0 break-words font-semibold">{t.topic}</span><span>{t.correct}/{t.total} correct · {t.percentage}%</span></li>)}</ul> : <p className="mt-4 text-sm">No tagged weak-topic summary is available from your submitted results.</p>}</section>
      <section className="mt-7"><h2 className="text-2xl font-semibold">Your attempt history</h2>{!data.history.attempts.length && <p className="card mt-4">No attempts yet.</p>}<ul className="mt-4 space-y-4">{data.history.attempts.map((a) => <li className="card flex flex-wrap items-center justify-between gap-4" key={a.id}><div className="min-w-0"><h3 className="break-words text-lg font-semibold">{a.title}</h3><p className="mt-2 text-sm text-muted">{a.status === "active" ? "In progress" : a.status === "timed_out" ? "Time ended" : "Submitted"} · Version {a.version} · {new Date(a.startedAt).toLocaleString()}</p>{a.result && <p className="mt-2 font-semibold">{a.result.correct}/{a.result.total} correct · {a.result.percentage}%</p>}</div><Link className="btn-secondary" to={`/assessment-attempts/${a.id}`}>{a.status === "active" ? "Resume attempt" : "View result"}</Link></li>)}</ul><nav aria-label="Attempt history pages" className="mt-5 flex flex-wrap items-center gap-3"><button className="btn-secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous page</button><span>Page {page}</span><button className="btn-secondary" disabled={page * 20 >= data.history.total} onClick={() => setPage(page + 1)}>Next page</button></nav></section>
    </>}
  </section>;
}
export default function StudentAssessmentsPage() { const { id } = useParams(); return <CourseAssessments key={id} id={id} />; }
