import { questionErrors, REVIEW_FLAGS } from "../services/questionImport.js";

export const editedQuestion = (q, patch) => ({ ...q, ...patch, ...(q.importReview && !patch.importReview ? { importReview: { ...q.importReview, checked: false } } : {}) });
export default function AssessmentQuestionFields({ question: q, number: n, onChange, onRemove, prefix = "", id }) {
  const label = (s) => prefix + s, errors = q.importReview ? questionErrors(q) : [];
  const update = (patch) => onChange(editedQuestion(q, patch));
  return <fieldset id={id} tabIndex={id ? -1 : undefined} className="min-w-0 scroll-mt-6 rounded-2xl border border-line p-4 sm:p-5"><legend className="px-2 font-semibold">{prefix}Question {n}</legend>
    {q.importReview && <div className="mb-4 rounded-xl border border-line p-3 text-sm leading-6"><p className="break-words font-semibold">Source: {q.importReview.source}</p>{q.importReview.confidence !== undefined && <p>OCR confidence: {q.importReview.confidence}%</p>}<ul className="mt-2 list-disc pl-5">{q.importReview.flags.map((flag) => <li key={flag}>{REVIEW_FLAGS[flag]}</li>)}</ul></div>}
    {q.importReview && q.options.length > 6 && <p role="alert" className="mb-4 text-sm leading-6 text-red-700 dark:text-red-300">{q.options.length} option lines were detected in this block. Questions may have merged. All options are retained below. Split the questions in the extracted PDF text and detect again, or remove only options you have checked against the source. This block cannot be added until it has 2–6 options.</p>}
    <label className="block text-sm font-semibold">Question text {n}<textarea aria-label={label(`Question text ${n}`)} className="input-field mt-2" rows={3} maxLength={1200} value={q.prompt} onChange={(e) => update({ prompt: e.target.value })} /></label>
    <div className="mt-4 space-y-3">{q.options.map((option, o) => <div className="flex items-end gap-2" key={o}><label className="min-w-0 flex-1 text-sm font-semibold">Question {n}, option {o + 1}<input aria-label={label(`Question ${n}, option ${o + 1}`)} className="input-field mt-2" maxLength={400} value={option} onChange={(e) => update({ options: q.options.map((v, i) => i === o ? e.target.value : v) })} /></label><button className="btn-secondary !px-3" type="button" disabled={q.options.length <= 2} aria-label={label(`Remove question ${n} option ${o + 1}`)} onClick={() => update({ options: q.options.filter((_, i) => i !== o), correctIndex: q.correctIndex === o ? null : q.correctIndex > o ? q.correctIndex - 1 : q.correctIndex })}>×</button></div>)}</div>
    <button className="btn-secondary mt-3" type="button" disabled={q.options.length >= 6} onClick={() => update({ options: [...q.options, ""] })}>Add option to question {n}</button>
    <label className="mt-4 block text-sm font-semibold">Correct answer for question {n}<select aria-label={label(`Correct answer for question ${n}`)} className="input-field mt-2" value={q.correctIndex ?? ""} onChange={(e) => update({ correctIndex: e.target.value === "" ? null : Number(e.target.value) })}><option value="">Choose the correct option</option>{q.options.map((_, o) => <option key={o} value={o}>Option {o + 1}</option>)}</select></label>
    <label className="mt-4 block text-sm font-semibold">Explanation for question {n} (optional)<textarea aria-label={label(`Explanation for question ${n}`)} className="input-field mt-2" rows={3} maxLength={2000} value={q.explanation ?? ""} onChange={(e) => update({ explanation: e.target.value })} /></label>
    <label className="mt-4 block text-sm font-semibold">Topic tag for question {n} (optional)<input aria-label={label(`Topic tag for question ${n} (optional)`)} className="input-field mt-2" maxLength={80} value={q.topic} onChange={(e) => update({ topic: e.target.value })} /></label>
    {q.importReview && <><ul className="mt-4 text-sm leading-6 text-red-700 dark:text-red-300">{errors.map((message) => <li key={message}>{message}</li>)}</ul><label className="mt-4 flex items-start gap-3 text-sm leading-6"><input type="checkbox" className="mt-1 shrink-0" aria-label={label(`Reviewed imported question ${n}`)} disabled={Boolean(errors.length)} checked={q.importReview.checked} onChange={(e) => update({ importReview: { ...q.importReview, checked: e.target.checked } })} /><span>I checked this question against the source and corrected its text, options, answer and any explanation provided. Any edit requires review again.</span></label></>}
    <button className="btn-danger mt-4" type="button" onClick={onRemove}>Remove {prefix ? "imported " : ""}question {n}</button>
  </fieldset>;
}
