import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, LockKeyhole, UserRound } from "lucide-react";
import { formatInr } from "../services/payments.js";
import CategoryBadge from "./CategoryBadge.jsx";
import CourseArtwork from "./CourseArtwork.jsx";
export default function CourseCard({ course, management = false, status }) {
  const needsEnrollment = !management && course.visibility === "public" && (course.access?.enrolled ?? course.access?.assigned) === false;
  const needsInstructor = !management && course.visibility !== "public" && course.access?.assigned === false;
  const locked = !management && !needsInstructor && (course.payment?.required ?? course.price > 0);
  const paymentLabels = { required: "Payment required", pending: "Payment pending", failed: "Payment failed", expired: "Checkout expired", refunded: "Payment refunded", partially_refunded: "Payment needs review", disputed: "Payment disputed", reversed: "Payment reversed" };
  const label = needsEnrollment ? "Enrollment available" : needsInstructor ? "Instructor access needed" : locked ? paymentLabels[course.payment?.status] || "Payment required" : status === "completed" ? "Completed" : status ? "Ready to learn" : course.archivedAt ? "Archived" : course.isPublished ? "Shared" : "Not shared";
  return <article className="card course-card flex h-full flex-col overflow-hidden !p-0"><div className="relative"><CourseArtwork course={course} className="aspect-[16/9]" /><span className="absolute right-3 top-3 inline-flex items-center gap-1.5 rounded-lg border border-white/60 bg-white/95 px-2.5 py-1.5 text-xs font-semibold text-primary-800 shadow-sm dark:border-slate-600 dark:bg-[#172829]/95 dark:text-primary-200">{needsInstructor || needsEnrollment || locked ? <LockKeyhole size={13} /> : status === "completed" && <CheckCircle2 size={13} />}{label}</span></div><div className="flex flex-1 flex-col p-5"><div><CategoryBadge category={course.category} /></div><h2 className="mt-3 font-display text-lg font-semibold break-words">{course.title}</h2>{course.instructor?.name && <p className="mt-2 flex items-center gap-1.5 text-xs text-slate-500 dark:text-slate-400"><UserRound size={13} />{course.instructor.name}</p>}<p className="mt-3 line-clamp-3 flex-1 text-sm leading-6 text-slate-600 dark:text-slate-300">{course.description}</p><p className="mt-4 text-sm font-semibold">{course.price > 0 ? formatInr(course.payment?.amountMinor ?? Math.round(course.price * 100)) : "Free"}{course.price > 0 && !management && course.payment?.paid && <span className="ml-2 font-normal text-primary-700 dark:text-primary-200">Paid</span>}</p><p className="mt-4 text-xs capitalize text-slate-500 dark:text-slate-400">{course.level} · {course.language || "English"}</p><Link className="btn-secondary mt-5 w-full justify-between gap-2 !text-primary-700 dark:!text-primary-200" to={management ? `/instructor/courses/${course._id}/curriculum` : needsInstructor || needsEnrollment || !(locked && course.payment?.orderId) ? `/courses/${course._id}` : `/payments/${course.payment.orderId}`}>{management ? course.archivedAt ? "View archived course" : "Manage curriculum" : needsEnrollment ? "Enroll in course" : needsInstructor ? "View course" : locked ? course.payment?.orderId ? "Review payment" : "Pay to unlock" : "Open course"}<ArrowRight size={16} /></Link></div></article>;
}
