export const publicCourseDefaults = { visibility: "private", examName: "", summary: "", audience: "", publicInstructorName: "", publicInstructorBio: "", supportEmail: "", supportUrl: "", termsUrl: "", privacyPolicyUrl: "", refundPolicyUrl: "", previewLesson: "" };
export function publicCourseValues(course) { return Object.fromEntries(Object.entries(publicCourseDefaults).map(([field, fallback]) => [field, course[field] || fallback])); }
export default function PublicCourseFields({ register, watch, lessons, disabled }) {
  const visibility = watch("visibility");
  const samples = lessons.filter((lesson) => lesson.contentType === "text" && lesson.content?.trim() || lesson.contentType === "video" && lesson.video?.status === "ready");
  return <fieldset disabled={disabled} className="space-y-5 border-t border-slate-200 pt-6 dark:border-slate-700"><legend className="pt-6 text-lg font-semibold">Public discovery</legend><p className="text-sm leading-6 text-slate-500 dark:text-slate-400">Choose whether visitors can see this course without signing in. Public courses share their title, description, cover, price and curriculum outline. Only the sample you choose shares lesson content.</p>
    <div className="grid gap-3 sm:grid-cols-2">{[["private", "Private", "Keep this course out of public discovery."], ["public", "Public", "Show this course to visitors when it is published."]].map(([value, title, description]) => <label key={value} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-4 ${visibility === value ? "border-primary-500 bg-primary-50 dark:bg-primary-900/20" : "border-slate-200 dark:border-slate-600"}`}><input className="mt-1 accent-teal-600" type="radio" aria-label={title} value={value} {...register("visibility")} /><span><span className="block text-sm font-semibold">{title}</span><span className="mt-1 block text-xs leading-5 text-slate-500 dark:text-slate-400">{description}</span></span></label>)}</div>
    <p className="text-xs leading-5 text-slate-500 dark:text-slate-400">Saving Public on an already published course makes its page and selected sample available immediately. This setting does not grant full lesson access. Published private courses remain visible in the signed-in student catalog under the existing access rules.</p>
    <label className="block text-sm font-medium">Exam or qualification name<input className="input-field mt-2" maxLength={120} {...register("examName")} /><span className="mt-1 block text-xs font-normal text-slate-500 dark:text-slate-400">Use the actual exam this course prepares students for.</span></label>
    <label className="block text-sm font-medium">Short course summary<textarea className="input-field mt-2 min-h-24" maxLength={500} {...register("summary")} /></label>
    <label className="block text-sm font-medium">Who this course is for<textarea className="input-field mt-2 min-h-24" maxLength={1000} {...register("audience")} /></label>
    <label className="block text-sm font-medium">Public sample lesson<select className="input-field mt-2" {...register("previewLesson")}><option value="">No public sample</option>{samples.map((lesson) => <option key={lesson._id} value={lesson._id}>{lesson.title} ({lesson.contentType})</option>)}</select><span className="mt-2 block text-xs font-normal leading-5 text-slate-500 dark:text-slate-400">Choose a text lesson with content or a completed MP4 upload from this course. Add lessons in the curriculum, then return here to choose a sample.</span></label>
    <details><summary className="cursor-pointer text-sm font-medium">Public instructor and contact details</summary><div className="mt-4 space-y-5"><p className="text-xs leading-5 text-slate-500 dark:text-slate-400">These details appear on the public course page. Your account profile and email are not copied automatically.</p><label className="block text-sm font-medium">Public instructor name<input className="input-field mt-2" maxLength={120} {...register("publicInstructorName")} /></label><label className="block text-sm font-medium">Public instructor bio<textarea className="input-field mt-2 min-h-28" maxLength={2000} {...register("publicInstructorBio")} /></label><label className="block text-sm font-medium">Public support email<input className="input-field mt-2" type="email" maxLength={254} {...register("supportEmail")} /></label><label className="block text-sm font-medium">Public support link<input className="input-field mt-2" type="url" placeholder="https://" maxLength={2000} {...register("supportUrl")} /></label></div></details>
    <details><summary className="cursor-pointer text-sm font-medium">Course policy links (optional)</summary><p className="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">Link to your actual policies using HTTPS. Blank fields do not create or imply a policy.</p><div className="mt-4 space-y-4">{[["termsUrl", "Terms link"], ["privacyPolicyUrl", "Privacy policy link"], ["refundPolicyUrl", "Refund policy link"]].map(([field, label]) => <label key={field} className="block text-sm font-medium">{label}<input className="input-field mt-2" type="url" placeholder="https://" maxLength={2000} {...register(field)} /></label>)}</div></details>
  </fieldset>;
}
