import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import StudyHero from "../../components/StudyHero.jsx";
import CourseArtwork from "../../components/CourseArtwork.jsx";
import axiosInstance, { errorMessage } from "../../services/axiosInstance.js";

export function coursePrice(amountMinor) {
  return amountMinor === 0 ? "Free" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: amountMinor % 100 ? 2 : 0 }).format(amountMinor / 100);
}
export default function PublicCatalogPage({ home = false }) {
  const [params, setParams] = useSearchParams();
  const q = params.get("q") || "", category = params.get("category") || "", page = Number(params.get("page") || 1);
  const [search, setSearch] = useState(q), [data, setData] = useState(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [retry, setRetry] = useState(0);
  useEffect(() => { setSearch(q); }, [q]);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError(""); setData(null);
    axiosInstance.get("/public/courses", { params: { q, category, page, limit: 12 }, signal: controller.signal }).then((response) => { if (!controller.signal.aborted) setData(response.data.data); }).catch((e) => { if (!controller.signal.aborted) setError(errorMessage(e)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [q, category, page, retry]);
  const filters = (changes) => { const next = new URLSearchParams(params); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, String(value)) : next.delete(key)); setParams(next); };
  return <>
    {home ? <><StudyHero /><div className="discovery-steps">{[["01", "Pehle syllabus.", "Course mein kya hai? Outline aur learning outcomes dekhein."], ["02", "Sample se samjhein.", "Jahan sample diya hai, learning style pehle try karein."], ["03", "Phir shuru karein.", "Enrollment policy dekhein. Instructor assignment aur paid course ki verified payment zaroori ho sakti hai."]].map(([n,title,copy]) => <section className="discovery-step" key={n}><span aria-hidden="true">{n}</span><div><h2>{title}</h2><p>{copy}</p></div></section>)}</div></> : <header className="catalog-intro mb-8"><p className="eyebrow">Government-exam learning</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">Aaj kya padhein?</h1><p className="mt-3 text-muted">Apne next step ke liye course chunein. Syllabus aur sample dekhein, phir decide karein.</p></header>}
    <section id="catalog" aria-labelledby="catalog-heading"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 id="catalog-heading" className="text-2xl font-semibold">Explore courses</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{data ? `${data.total} ${data.total === 1 ? "course" : "courses"} available to explore` : "Published courses and their available samples"}</p></div></div>
      <form role="search" className="catalog-filters mt-6 flex flex-wrap items-end gap-3" onSubmit={(event) => { event.preventDefault(); filters({ q: search.trim(), page: "" }); }}><label className="min-w-0 flex-[2_1_220px] text-sm font-medium">Search courses<input className="input-field mt-2" type="search" maxLength={100} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Course or exam name" /></label><label className="min-w-0 flex-[1_1_180px] text-sm font-medium">Category<select aria-label="Category" className="input-field mt-2" value={category} onChange={(event) => filters({ category: event.target.value, page: "" })}><option value="">All categories</option>{data?.categories?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="btn-primary">Search</button>{(q || category) && <button className="btn-secondary" type="button" onClick={() => setParams({})}>Clear filters</button>}</form>
      {loading && <p role="status" className="card mt-6">Loading courses…</p>}
      {error && <div role="alert" className="card mt-6"><p>{error}</p><button className="btn-secondary mt-4" onClick={() => setRetry((value) => value + 1)}>Retry courses</button></div>}
      {data && !data.courses.length && <div className="card mt-6"><h3 className="font-semibold">{q || category || page > 1 ? "No courses match these filters" : "Courses will appear here when published"}</h3><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{q || category || page > 1 ? "Try another search or clear the filters to see available courses." : "No published, unarchived courses are available yet."}</p></div>}
      {data && <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.courses.map((course) => <article key={course.id} className="card course-card public-course-card flex min-w-0 flex-col !p-0 overflow-hidden"><CourseArtwork course={course} className="aspect-video w-full" /><div className="flex flex-1 flex-col p-5"><p className="course-category text-xs font-semibold text-primary-700 dark:text-primary-300">{course.examName || course.category?.name || "Course"}</p><h3 className="mt-2 break-words text-xl font-semibold"><Link className="hover:underline" to={`/catalog/${encodeURIComponent(course.slug)}`}>{course.title}</Link></h3>{course.summary && <p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{course.summary}</p>}<div className="mt-4 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-500 dark:text-slate-400">{course.language && <span>{course.language}</span>}{course.hasPreview && <span>Sample available</span>}<span>{!course.availability ? "Check availability" : !course.availability.ready ? "Materials being prepared" : course.availability.enrollment === "public" ? "Open enrollment" : "Instructor assignment required"}</span></div><div className="mt-auto flex flex-wrap items-center justify-between gap-3 pt-6"><strong>{coursePrice(course.amountMinor)}</strong><Link className="btn-secondary" to={`/catalog/${encodeURIComponent(course.slug)}`}>View course</Link></div></div></article>)}</div>}
      {data?.total > data?.limit && <nav aria-label="Course pages" className="mt-7 flex flex-wrap items-center justify-center gap-4"><button className="btn-secondary" disabled={page <= 1} onClick={() => filters({ page: page - 1 })}>Previous</button><span className="text-sm">Page {page} of {Math.ceil(data.total / data.limit)}</span><button className="btn-secondary" disabled={page * data.limit >= data.total} onClick={() => filters({ page: page + 1 })}>Next</button></nav>}
    </section>
  </>;
}
