import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowUpRight, BookOpen } from "lucide-react";
import CourseArtwork from "../../components/CourseArtwork.jsx";
import axiosInstance, { errorMessage } from "../../services/axiosInstance.js";

export function coursePrice(amountMinor) {
  return amountMinor === 0 ? "Free" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: amountMinor % 100 ? 2 : 0 }).format(amountMinor / 100);
}
export default function PublicCatalogPage({ home = false }) {
  const [params, setParams] = useSearchParams();
  const q = params.get("q") || "", category = params.get("category") || "", page = Number(params.get("page") || 1);
  const [search, setSearch] = useState(q), [data, setData] = useState(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [retry, setRetry] = useState(0);
  useEffect(() => { setSearch(q); }, [q]);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError(""); setData(null);
    axiosInstance.get("/public/courses", { params: { q, category, page, limit: 12 }, signal: controller.signal }).then((response) => { if (!controller.signal.aborted) setData(response.data.data); }).catch((e) => { if (!controller.signal.aborted) setError(errorMessage(e)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [q, category, page, retry]);
  const filters = (changes) => { const next = new URLSearchParams(params); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, String(value)) : next.delete(key)); setParams(next); };
  return <>
    {home ? <section className="grid gap-8 pb-12 lg:grid-cols-[1.5fr_1fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-primary-700 dark:text-primary-300">Learn for your next step</p><h1 className="mt-5 max-w-3xl text-4xl font-semibold leading-tight sm:text-6xl">Build your knowledge.<br /><span className="text-primary-700 dark:text-primary-300">Prepare with purpose.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-slate-600 dark:text-slate-300">Explore courses for government-exam students and aspirants. See what each course covers and try an available sample before you decide.</p><a className="btn-primary mt-7 gap-2" href="#catalog">Explore courses <ArrowUpRight size={18} /></a></div><div className="card bg-primary-50/50 dark:bg-primary-900/10"><BookOpen className="text-primary-700 dark:text-primary-300" size={32} /><h2 className="mt-5 text-xl font-semibold">Know what you’re choosing</h2><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">Review the syllabus, teaching language, price and learning outcomes in one place. Course pages include the instructor’s public details and a sample when provided.</p></div></section> : <div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.15em] text-primary-700 dark:text-primary-300">Government-exam learning</p><h1 className="mt-3 text-4xl font-semibold">Find your course</h1><p className="mt-3 text-slate-600 dark:text-slate-300">Choose a course that matches the knowledge you want to build.</p></div>}
    <section id="catalog" aria-labelledby="catalog-heading"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 id="catalog-heading" className="text-2xl font-semibold">Explore courses</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{data ? `${data.total} ${data.total === 1 ? "course" : "courses"} available to explore` : "Published courses and their available samples"}</p></div></div>
      <form role="search" className="mt-6 flex flex-wrap items-end gap-3" onSubmit={(event) => { event.preventDefault(); filters({ q: search.trim(), page: "" }); }}><label className="min-w-0 flex-[2_1_220px] text-sm font-medium">Search courses<input className="input-field mt-2" type="search" maxLength={100} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Course or exam name" /></label><label className="min-w-0 flex-[1_1_180px] text-sm font-medium">Category<select aria-label="Category" className="input-field mt-2" value={category} onChange={(event) => filters({ category: event.target.value, page: "" })}><option value="">All categories</option>{data?.categories?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="btn-primary">Search</button>{(q || category) && <button className="btn-secondary" type="button" onClick={() => setParams({})}>Clear filters</button>}</form>
      {loading && <p role="status" className="card mt-6">Loading courses…</p>}
      {error && <div role="alert" className="card mt-6"><p>{error}</p><button className="btn-secondary mt-4" onClick={() => setRetry((value) => value + 1)}>Retry courses</button></div>}
      {data && !data.courses.length && <div className="card mt-6"><h3 className="font-semibold">{q || category || page > 1 ? "No courses match these filters" : "Courses will appear here when published"}</h3><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{q || category || page > 1 ? "Try another search or clear the filters to see available courses." : "The instructor has not published a course for public discovery yet."}</p></div>}
      {data && <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.courses.map((course) => <article key={course.id} className="card flex min-w-0 flex-col !p-0 overflow-hidden"><CourseArtwork course={course} className="aspect-video w-full" /><div className="flex flex-1 flex-col p-5"><p className="text-xs font-medium text-primary-700 dark:text-primary-300">{course.examName || course.category?.name || "Course"}</p><h3 className="mt-2 break-words text-xl font-semibold"><Link className="hover:underline" to={`/catalog/${encodeURIComponent(course.slug)}`}>{course.title}</Link></h3>{course.summary && <p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{course.summary}</p>}<div className="mt-4 flex flex-wrap gap-x-3 gap-y-1 text-xs text-slate-500 dark:text-slate-400">{course.language && <span>{course.language}</span>}{course.hasPreview && <span>Sample available</span>}</div><div className="mt-auto flex flex-wrap items-center justify-between gap-3 pt-6"><strong>{coursePrice(course.amountMinor)}</strong><Link className="btn-secondary" to={`/catalog/${encodeURIComponent(course.slug)}`}>View course</Link></div></div></article>)}</div>}
      {data?.total > data?.limit && <nav aria-label="Course pages" className="mt-7 flex flex-wrap items-center justify-center gap-4"><button className="btn-secondary" disabled={page <= 1} onClick={() => filters({ page: page - 1 })}>Previous</button><span className="text-sm">Page {page} of {Math.ceil(data.total / data.limit)}</span><button className="btn-secondary" disabled={page * data.limit >= data.total} onClick={() => filters({ page: page + 1 })}>Next</button></nav>}
    </section>
  </>;
}
