import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowRight, BookOpen, Check, Clock3, Film, Plus, RefreshCw, Search, ShieldCheck, Users, X } from "lucide-react";
import axiosInstance, { errorMessage } from "../../services/axiosInstance.js";
import LoadingSkeleton from "../../components/LoadingSkeleton.jsx";
import PrivateVideoPlayer from "../../components/PrivateVideoPlayer.jsx";
import { trapDialogFocus } from "../../components/dialogFocus.js";

const tabs = [{ key: "users", label: "People", icon: Users }, { key: "courses", label: "Courses", icon: BookOpen }, { key: "videos", label: "Videos", icon: Film }, { key: "activity", label: "Activity", icon: Clock3 }];
const date = (value) => value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "—";
const bytes = (value) => value ? `${(value / 1024 ** 2).toFixed(1)} MB` : "—";
function Badge({ children, muted = false }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-medium ${muted ? "bg-slate-100 text-slate-500 dark:bg-[#303035] dark:text-slate-400" : "bg-primary-50 text-primary-700 dark:bg-primary-900/60 dark:text-primary-200"}`}>{children}</span>; }
function Dialog({ title, busy, onClose, children }) {
  const ref = useRef(null);
  useEffect(() => { const dialog = ref.current; dialog.showModal(); return () => dialog.close(); }, []);
  return <dialog ref={ref} tabIndex={-1} onKeyDown={trapDialogFocus} className="admin-dialog" aria-labelledby="admin-dialog-title" onCancel={(event) => { event.preventDefault(); if (!busy) onClose(); }}>
    <div className="mb-5 flex items-start justify-between gap-4"><h2 id="admin-dialog-title" className="text-xl font-semibold">{title}</h2><button className="btn-secondary h-9 w-9 shrink-0 p-0" type="button" onClick={onClose} disabled={busy} aria-label="Close dialog"><X size={18} /></button></div>{children}
  </dialog>;
}

export default function AdminPage() {
  const [params, setParams] = useSearchParams();
  const tab = tabs.some((item) => item.key === params.get("tab")) ? params.get("tab") : "users";
  const [overview, setOverview] = useState(null);
  const [data, setData] = useState(null);
  const [search, setSearch] = useState(""); const [query, setQuery] = useState("");
  const [archived, setArchived] = useState(false);
  const [role, setRole] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [dialog, setDialog] = useState(null); const [busy, setBusy] = useState(false); const [dialogError, setDialogError] = useState("");
  const [instructors, setInstructors] = useState([]); const [instructorSearch, setInstructorSearch] = useState("");
  const [instructorLoading, setInstructorLoading] = useState(false);
  const request = useRef(0);
  const load = useCallback(async () => {
    const version = ++request.current; setLoading(true); setError("");
    try {
      const [summary, list] = await Promise.all([axiosInstance.get("/admin/overview"), axiosInstance.get(`/admin/${tab}`, { params: { page, limit: 20, ...(tab === "courses" ? { archived } : {}), ...(query && tab !== "activity" ? { search: query } : {}), ...(tab === "users" ? { role: role || undefined, status: status || undefined } : {}) } })]);
      if (version !== request.current) return;
      setOverview(summary.data.data); setData(list.data.data);
    } catch (e) { if (version === request.current) { setData(null); setError(errorMessage(e)); } }
    finally { if (version === request.current) setLoading(false); }
  }, [tab, page, query, role, status, archived]);
  useEffect(() => { load(); const counter = request; return () => { counter.current++; }; }, [load]);
  const open = (value) => { setDialogError(""); setInstructorSearch(""); setInstructors([]); setDialog(value); };
  const close = () => { setDialog(null); setDialogError(""); setInstructors([]); };
  const chooseTab = (value) => { setPage(1); setArchived(false); setQuery(""); setSearch(""); setRole(""); setStatus(""); setParams({ tab: value }); };
  useEffect(() => {
    if (dialog?.type !== "transfer") return;
    const controller = new AbortController(); setInstructorLoading(true);
    const timer = setTimeout(() => axiosInstance.get("/admin/users", { params: { role: "instructor", status: "active", search: instructorSearch, limit: 100 }, signal: controller.signal })
      .then(({ data: response }) => { setInstructors(response.data.users); setDialogError(""); })
      .catch((e) => { if (!controller.signal.aborted) setDialogError(errorMessage(e)); })
      .finally(() => { if (!controller.signal.aborted) setInstructorLoading(false); }), 200);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [dialog?.type, instructorSearch]);
  const submit = async (event) => {
    event.preventDefault(); setBusy(true); setDialogError("");
    const fields = new FormData(event.currentTarget);
    try {
      let result;
      if (dialog.type === "create") result = await axiosInstance.post("/admin/instructors", { name: fields.get("name"), email: fields.get("email"), temporaryPassword: fields.get("temporaryPassword") });
      if (dialog.type === "password") result = await axiosInstance.post(`/admin/users/${dialog.user.id}/temporary-password`, { temporaryPassword: fields.get("temporaryPassword") });
      if (dialog.type === "access") result = await axiosInstance.patch(`/admin/users/${dialog.user.id}/access`, { status: dialog.user.status === "suspended" ? "active" : "suspended" });
      if (dialog.type === "transfer") result = await axiosInstance.patch(`/admin/courses/${dialog.course._id}/instructor`, { instructorId: fields.get("instructorId") });
      if (dialog.type === "delete") result = await axiosInstance.delete(`/admin/courses/${dialog.course._id}`);
      setNotice(result.data.message); close(); await load();
    } catch (e) { setDialogError(errorMessage(e)); } finally { setBusy(false); }
  };
  const users = data?.users || []; const courses = data?.courses || []; const videos = data?.videos || []; const events = data?.events || [];
  const empty = !loading && data && !(users.length || courses.length || videos.length || events.length);
  const cards = [{ label: "Instructors", value: overview?.instructors, note: "Admin-created accounts", icon: ShieldCheck }, { label: "Students", value: overview?.students, note: `${overview?.suspended ?? "—"} accounts paused`, icon: Users }, { label: "Courses", value: overview?.courses, note: `${overview?.published ?? "—"} shared`, icon: BookOpen }, { label: "Videos", value: overview?.videos, note: `${overview?.ready ?? "—"} ready to play`, icon: Film }];
  return <section>
    <div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-primary-600 dark:text-primary-300">Administration</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Your learning workspace.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500 dark:text-slate-400">Manage the people, courses, and videos behind every lesson. Instructor access starts with you.</p></div><button className="btn-primary gap-2" onClick={() => open({ type: "create" })}><Plus size={17} />Create instructor</button></div>
    {loading && !overview ? <LoadingSkeleton variant="stats" label="Loading platform overview…" /> : <div className="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(({ label, value, note, icon: Icon }) => <div className="card stat-card !p-5" key={label}><div className="flex items-center justify-between text-slate-500 dark:text-slate-400"><span className="text-sm">{label}</span><Icon size={19} className="text-primary-600 dark:text-primary-300" /></div><p className="mt-3 text-3xl font-semibold tabular-nums">{value ?? "—"}</p><p className="mt-2 text-xs leading-5 text-slate-500 dark:text-slate-400">{note}</p></div>)}</div>}
    {notice && <div role="status" className="mt-5 flex items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200"><Check size={18} className="shrink-0" /><p className="flex-1">{notice}</p><button aria-label="Dismiss notification" onClick={() => setNotice("")}><X size={16} /></button></div>}
    <div className="mt-8 flex flex-wrap items-center justify-between gap-3"><nav aria-label="Admin sections" className="flex max-w-full gap-1 overflow-x-auto rounded-xl bg-slate-100 p-1 dark:bg-[#172829]">{tabs.map(({ key, label, icon: Icon }) => <button key={key} aria-current={tab === key ? "page" : undefined} onClick={() => chooseTab(key)} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-medium ${tab === key ? "bg-white text-slate-900 shadow-sm dark:bg-[#264140] dark:text-white" : "text-slate-500 dark:text-slate-400"}`}><Icon size={16} /><span>{label}</span></button>)}</nav><button className="btn-secondary gap-2" disabled={loading} onClick={load}><RefreshCw size={15} className={loading ? "animate-spin" : ""} />Refresh</button></div>
    <div className="admin-workspace mt-4"><div className="card !p-0 overflow-hidden">
      <div className="panel-heading"><h2 className="text-lg font-semibold">{tab === "users" ? "People" : tabs.find((item) => item.key === tab)?.label}</h2><span className="text-xs text-slate-500 dark:text-slate-400">{data ? `${data.total} in your workspace` : "Loading workspace…"}</span></div>
      <div className="border-b border-slate-100 p-5 dark:border-[#303035]">
        {tab === "activity" ? <p className="text-sm text-slate-500 dark:text-slate-400">Admin actions are recorded without passwords, cookies, or private video links. Pending entries need review if a request was interrupted.</p> : <form className="flex flex-wrap items-center gap-3" onSubmit={(e) => { e.preventDefault(); setPage(1); setQuery(search.trim()); }}><label className="relative min-w-48 flex-1"><span className="sr-only">{tab === "users" ? "Search name or email" : tab === "videos" ? "Search video filename" : "Search course title"}</span><Search className="pointer-events-none absolute left-3.5 top-3.5 text-slate-400" size={17} /><input className="input-field !pl-10" value={search} onChange={(e) => setSearch(e.target.value)} maxLength={100} placeholder={tab === "users" ? "Search name or email…" : tab === "videos" ? "Search filename…" : "Search course title…"} /></label>{tab === "courses" && <label><span className="sr-only">Course status</span><select className="input-field" value={String(archived)} onChange={(e) => { setArchived(e.target.value === "true"); setPage(1); }}><option value="false">Active courses</option><option value="true">Archived courses</option></select></label>}{tab === "users" && <><label><span className="sr-only">Filter role</span><select className="input-field" value={role} onChange={(e) => { setRole(e.target.value); setPage(1); }}><option value="">All roles</option><option value="instructor">Instructors</option><option value="student">Students</option><option value="admin">Administrators</option></select></label><label><span className="sr-only">Filter access</span><select className="input-field" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All access</option><option value="active">Active</option><option value="suspended">Paused</option></select></label></>}<button className="btn-secondary" type="submit">Search</button></form>}
      </div>
      {error && <p role="alert" className="p-6 text-sm text-red-700 dark:text-red-300">{error} Use Refresh to retry.</p>}
      {loading && <div className="p-5"><LoadingSkeleton variant="rows" label={`Loading ${tab === "users" ? "accounts" : tab}…`} /></div>}
      {empty && <div className="px-6 py-14 text-center"><Users className="mx-auto text-slate-400" size={28} /><h2 className="mt-4 text-lg font-semibold">No {tab === "users" ? "accounts" : tab} to show</h2><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{query || role || status ? "Try a different search or filter." : tab === "users" ? "Create an instructor to start your teaching team." : "New items will appear here as your workspace grows."}</p></div>}
      {!loading && tab === "users" && users.map((user) => <article className="admin-list-row" key={user.id}><div className="flex min-w-0 items-start gap-3"><span aria-hidden="true" className="admin-avatar">{user.name.slice(0, 1).toUpperCase()}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold break-words">{user.name}</h2><Badge muted={user.role === "student"}>{user.role}</Badge>{user.status === "suspended" && <Badge muted>Access paused</Badge>}</div><p className="mt-1 break-all text-sm text-slate-500 dark:text-slate-400">{user.email}</p><p className="mt-2 text-xs text-slate-500 dark:text-slate-400">{user.mustChangePassword ? `Password change required · temporary password expires ${date(user.temporaryPasswordExpiresAt)}` : `Joined ${date(user.createdAt)}`}</p></div></div><div className="flex shrink-0 flex-wrap gap-2">{user.role === "admin" ? <span className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400"><ShieldCheck size={15} />Protected account</span> : <>{user.role === "instructor" && <button className="btn-secondary !px-3 !py-2 text-xs" onClick={() => open({ type: "password", user })}>Reset password</button>}<button className={`btn-secondary !px-3 !py-2 text-xs ${user.status === "suspended" ? "" : "!text-red-700 dark:!text-red-300"}`} onClick={() => open({ type: "access", user })}>{user.status === "suspended" ? "Restore access" : "Pause access"}</button></>}</div></article>)}
      {!loading && tab === "courses" && courses.map((course) => <article className="admin-list-row" key={course._id}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold break-words">{course.title}</h2><Badge muted={!course.isPublished}>{course.archivedAt ? "Archived" : course.isPublished ? "Shared" : "Not shared"}</Badge></div><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{course.instructor?.name || "Owner unavailable"} · {course.category?.name || "Uncategorized"}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Updated {date(course.updatedAt)}</p></div><div className="flex shrink-0 flex-wrap gap-2">{!course.archivedAt && <button className="btn-secondary !px-3 !py-2 text-xs" onClick={() => open({ type: "transfer", course })}>Change instructor</button>}<button className="btn-secondary !px-3 !py-2 text-xs !text-red-700 dark:!text-red-300" onClick={() => open({ type: "delete", course })}>Delete course</button><Link className="btn-secondary gap-2 !px-3 !py-2 text-xs" to={`/instructor/courses/${course._id}/curriculum`}>Manage access & lessons<ArrowRight size={14} /></Link></div></article>)}
      {!loading && tab === "videos" && videos.map((video) => <article className="admin-list-row" key={video.id}><div className="flex min-w-0 items-start gap-3"><span className="admin-avatar"><Film size={20} /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="break-all font-semibold">{video.filename || "Untitled upload"}</h2><Badge muted={video.status !== "ready"}>{video.status}</Badge></div><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{video.course?.title || "Course removed"} · {video.lesson?.title || "Lesson removed"}</p><p className="mt-2 text-xs text-slate-500 dark:text-slate-400">{bytes(video.size)} · {video.owner?.name || "Uploader unavailable"} · {date(video.createdAt)}{!video.attached ? " · Detached from lesson" : ""}</p></div></div><div className="flex shrink-0 gap-2">{video.attached && video.status === "ready" && !video.course?.archived && video.lesson && <button className="btn-secondary !px-3 !py-2 text-xs" onClick={() => open({ type: "preview", video })}>Preview</button>}{video.course && <Link className="btn-secondary !px-3 !py-2 text-xs" to={`/instructor/courses/${video.course.id}/curriculum`}>Manage lesson</Link>}</div></article>)}
      {!loading && tab === "activity" && events.map((event) => <article className="admin-list-row" key={event.id}><div className="min-w-0"><h2 className="text-sm font-semibold">{event.action}</h2><p className="mt-1 break-all text-xs text-slate-500 dark:text-slate-400">{event.actor?.name || "Operator"} · {new Date(event.createdAt).toLocaleString()}{event.method ? ` · ${event.method} ${event.path}` : ""}</p></div><Badge muted={event.outcome !== "succeeded"}>{event.outcome}</Badge></article>)}
      {data && <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-5 py-4 dark:border-[#303035]"><p className="text-xs text-slate-500 dark:text-slate-400">{data.total} total · Page {data.page} of {Math.max(1, Math.ceil(data.total / data.limit))}</p><div className="flex gap-2"><button className="btn-secondary !px-3 !py-2 text-xs" disabled={loading || page === 1} onClick={() => setPage(page - 1)}>Previous</button><button className="btn-secondary !px-3 !py-2 text-xs" disabled={loading || page * data.limit >= data.total} onClick={() => setPage(page + 1)}>Next</button></div></div>}
    </div>
    <aside className="card h-fit"><p className="eyebrow">Workspace guide</p><h2 className="mt-2 text-lg font-semibold">A good course starts here.</h2><p className="mt-3 text-sm leading-6 text-slate-500 dark:text-slate-400">Give instructors a place to teach, then help students find their next lesson.</p><ol className="workspace-steps mt-5"><li><span>01</span><div><h3>Build your teaching team</h3><p>Create instructor accounts and share their temporary sign-in details privately.</p></div></li><li><span>02</span><div><h3>Add something to learn</h3><p>Upload a lesson or a PDF handout to a course.</p></div></li><li><span>03</span><div><h3>Choose your students</h3><p>Published courses are visible to every student. Assign students to private courses, or enable public enrollment from course details. Paid materials also require verified payment.</p></div></li></ol><Link className="btn-secondary mt-6 w-full gap-2" to="/admin/courses/upload">Create a course<ArrowRight size={16} /></Link></aside></div>
    <p className="mt-5 text-xs leading-5 text-slate-500 dark:text-slate-400">Published courses are visible to every student. Learning materials require an instructor assignment or public enrollment, plus verified payment when the course is paid. Pausing an account revokes its sessions; previously issued video links may remain usable briefly. Existing instructors stay active until you review them.</p>
    {dialog && <Dialog busy={busy} onClose={close} title={dialog.type === "create" ? "Create an instructor" : dialog.type === "password" ? "Set a temporary password" : dialog.type === "access" ? `${dialog.user.status === "suspended" ? "Restore" : "Pause"} account access` : dialog.type === "transfer" ? "Change course instructor" : dialog.type === "delete" ? "Delete this course" : dialog.video.lesson.title}>
      {dialog.type === "preview" ? <PrivateVideoPlayer lessonId={dialog.video.lesson.id} title={dialog.video.lesson.title} /> : <form onSubmit={submit} className="space-y-4">
        {dialog.type === "create" && <><p className="text-sm leading-6 text-slate-500 dark:text-slate-400">Create the account, then share its email and temporary password privately. The instructor must choose a new password before opening courses.</p><label className="block text-sm font-medium">Full name<input required name="name" autoComplete="off" maxLength={100} className="input-field mt-2" disabled={busy} /></label><label className="block text-sm font-medium">Email address<input required name="email" type="email" autoComplete="off" maxLength={254} className="input-field mt-2" disabled={busy} /></label></>}
        {dialog.type === "password" && <p className="text-sm leading-6 text-slate-500 dark:text-slate-400">Set a new temporary password for <strong className="text-slate-900 dark:text-white">{dialog.user.name}</strong> ({dialog.user.email}). This signs out their existing sessions. A paused account stays paused.</p>}
        {["create", "password"].includes(dialog.type) && <><label className="block text-sm font-medium">Temporary password<input required type="password" name="temporaryPassword" autoComplete="new-password" minLength={12} maxLength={72} className="input-field mt-2" aria-describedby="temporary-password-help" disabled={busy} /></label><p id="temporary-password-help" className="text-xs leading-5 text-slate-500 dark:text-slate-400">12+ characters, at most 72 UTF-8 bytes. Save it securely before continuing; it will not be shown again. It expires in 72 hours. No email is sent automatically.</p></>}
        {dialog.type === "access" && <p className="text-sm leading-6 text-slate-500 dark:text-slate-400">{dialog.user.status === "suspended" ? <>Restore access for <strong>{dialog.user.name}</strong>? They will need to sign in again. Their courses and assignments are preserved.</> : <>Pause access for <strong>{dialog.user.name}</strong>? They will be signed out and unable to sign in or request new video links. Courses and assignments are preserved; published courses remain available to other assigned students.</>}</p>}
        {dialog.type === "delete" && <p className="text-sm leading-6 text-slate-500 dark:text-slate-400">Delete <strong>{dialog.course.title}</strong> permanently? It disappears for every student and instructor. Lessons, videos, notes, and assignments for this course are removed and cannot be restored.</p>}
        {dialog.type === "transfer" && <><p className="text-sm leading-6 text-slate-500 dark:text-slate-400">Transfer <strong>{dialog.course.title}</strong> from {dialog.course.instructor?.name || "its current owner"}. The new instructor gets management access; the previous instructor loses it. Student assignments stay in place. Finish or remove pending uploads first.</p><label className="block text-sm font-medium">Find an active instructor<input className="input-field mt-2" value={instructorSearch} onChange={(e) => setInstructorSearch(e.target.value)} maxLength={100} disabled={busy} placeholder="Search by name or email" /></label><label className="block text-sm font-medium">New instructor<select name="instructorId" required className="input-field mt-2" defaultValue="" disabled={busy || instructorLoading}><option value="">{instructorLoading ? "Loading instructors…" : "Choose an instructor"}</option>{instructors.map((user) => <option key={user.id} value={user.id}>{user.name} — {user.email}</option>)}</select></label><p className="text-xs text-slate-500 dark:text-slate-400">Showing up to 100 matches. Refine your search if needed.</p></>}
        {dialogError && <p role="alert" className="text-sm text-red-700 dark:text-red-300">{dialogError}</p>}
        <div className="flex justify-end gap-3 pt-3"><button type="button" className="btn-secondary" disabled={busy} onClick={close}>Cancel</button><button className="btn-primary" disabled={busy || (dialog.type === "transfer" && instructorLoading)}>{busy ? "Saving…" : dialog.type === "create" ? "Create instructor" : dialog.type === "password" ? "Replace password" : dialog.type === "transfer" ? "Transfer course" : dialog.type === "delete" ? "Delete course" : dialog.user.status === "suspended" ? "Restore access" : "Pause access"}</button></div>
      </form>}
    </Dialog>}
  </section>;
}
