import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import axiosInstance, { errorMessage } from "../../services/axiosInstance.js";
import { formatInr } from "../../services/payments.js";
import { useDecision } from "../../components/DecisionProvider.jsx";
import WorkspaceIntro from "../../components/WorkspaceIntro.jsx";
export default function AcquisitionPage() {
  const { id } = useParams(), decide = useDecision(), prefix = `/courses/${id}/acquisition`;
  const [data, setData] = useState(null), [settings, setSettings] = useState(null), [reviewed, setReviewed] = useState(false), [label, setLabel] = useState(""), [channel, setChannel] = useState("referral"), [page, setPage] = useState(1), [error, setError] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const request = useRef(null), action = useRef(null), pending = useRef(false), attempt = useRef(null);
  const load = useCallback(async () => { request.current?.abort(); const controller = new AbortController(); request.current = controller;
    try { const results = await Promise.all(["config", "sources", "report", `interest?page=${page}`].map((path) => axiosInstance.get(`${prefix}/${path}`, { signal: controller.signal }))); if (!controller.signal.aborted) { const [config, sources, report, interest] = results.map((r) => r.data.data); setData({ ...config, ...sources, report, interest }); setSettings(config.config); setReviewed(false); setError(""); } }
    catch (e) { if (!controller.signal.aborted) setError(errorMessage(e)); }
  }, [prefix, page]);
  useEffect(() => { load(); return () => { request.current?.abort(); action.current?.abort(); }; }, [load]);
  const mutate = async (method, path, body, success) => { if (pending.current) return; pending.current = true; setBusy(true); setError(""); setMessage(""); const controller = new AbortController(); action.current = controller;
    try { await axiosInstance({ method, url: `${prefix}/${path}`, data: body, signal: controller.signal }); if (!controller.signal.aborted) { setMessage(success); await load(); return true; } }
    catch (e) { if (!controller.signal.aborted) setError(errorMessage(e)); } finally { pending.current = false; if (!controller.signal.aborted) setBusy(false); }
    return false;
  };
  if (!data) return <section className="card">{error ? <div role="alert"><p>{error}</p><button className="btn-secondary mt-4" onClick={load}>Retry acquisition report</button></div> : <p role="status">Loading course acquisition…</p>}</section>;
  const dirty = settings.measurementEnabled !== data.config.measurementEnabled || settings.interestEnabled !== data.config.interestEnabled || reviewed;
  const canEnable = Boolean(data.config.policyUrl), totals = data.report.totals;
  return <section><Link className="text-sm underline" to={`/instructor/courses/${id}/curriculum`}>← Course curriculum</Link><WorkspaceIntro eyebrow="Optional acquisition" title="Sources and course interest" >{data.course.title}</WorkspaceIntro>
    {error && <p role="alert" className="card mt-5 text-red-700 dark:text-red-300">{error}</p>}{message && <p role="status" className="card mt-5">{message}</p>}
    <form className="card mt-5" onSubmit={(e) => { e.preventDefault(); mutate("put", "config", { measurementEnabled: settings.measurementEnabled, interestEnabled: settings.interestEnabled, policyReviewed: reviewed, version: data.config.version }, "Collection settings saved."); }}><h2 className="text-xl font-semibold">Collection settings</h2><p className="mt-3 text-sm leading-7 text-muted">Collection starts off. Review your actual notice, contact purpose, authorized access and {data.config.retentionDays}-day retention before enabling it. Changing the notice requires another review. No messages are sent by this feature.</p>
      {!canEnable ? <p className="mt-3 text-sm">Add your actual privacy notice in <Link className="underline" to={`/instructor/courses/${id}/edit`}>course details</Link> before enabling collection.</p> : <a href={data.config.policyUrl} className="mt-3 inline-block text-sm underline" target="_blank" rel="noopener noreferrer">Review actual privacy notice</a>}
      <fieldset disabled={busy} className="mt-4 min-w-0 space-y-2"><label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" disabled={!canEnable} checked={settings.measurementEnabled} onChange={(e) => setSettings({ ...settings, measurementEnabled: e.target.checked })} />Offer optional visit and enrollment source measurement</label><label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" disabled={!canEnable} checked={settings.interestEnabled} onChange={(e) => setSettings({ ...settings, interestEnabled: e.target.checked })} />Offer course information and demo interest requests</label><label className="flex min-h-12 items-start gap-3 text-sm leading-6"><input className="mt-1" type="checkbox" checked={reviewed} onChange={(e) => setReviewed(e.target.checked)} />I reviewed this notice for these purposes, access, retention and optional marketing consent.</label></fieldset><div className="mt-4 flex flex-wrap gap-3"><button className="btn-primary" disabled={busy || !dirty || ((settings.measurementEnabled || settings.interestEnabled) && !reviewed)}>Save collection settings</button><button type="button" className="btn-secondary" disabled={busy} onClick={async () => { if (dirty && !await decide({ title: "Discard unsaved collection settings?", body: "Reload the settings currently saved on the server?", confirmLabel: "Reload settings" })) return; load(); }}>Refresh report and settings</button></div>
    </form>
    <section className="card mt-5"><h2 className="text-xl font-semibold">Recorded course activity</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2">{[["Retained consented page views", totals.visits], ["Recorded public free enrollments", totals.freeEnrollments], ["Recorded public enrollments with paid live orders", totals.livePaidEnrollments], ["Live recorded receipts before fees and taxes", formatInr(totals.receiptsMinor)]].map(([title, count]) => <div key={title}><dt className="text-sm text-muted">{title}</dt><dd className="mt-1 text-2xl font-semibold">{count}</dd></div>)}</dl><p className="mt-4 text-sm leading-7">Live order states: paid {totals.paidOrders} · partial refunds {totals.partialRefunds} · full refunds {totals.fullRefunds} · disputes {totals.disputes} · reversals {totals.reversals}.</p><details className="mt-5"><summary className="cursor-pointer font-semibold">What these counts mean</summary>{Object.entries(data.report.definitions).map(([key, text]) => <p key={key} className="mt-3 text-sm leading-7 text-muted">{text}</p>)}</details><p className="mt-3 text-xs text-muted">Updated {new Date(data.report.generatedAt).toLocaleString()}. No conversion rate is calculated.</p></section>
    <section className="card mt-5"><h2 className="text-xl font-semibold">Source links</h2><p className="mt-3 text-sm leading-7 text-muted">Up to 20 retained campaign links per course, without rewards or discounts. Use generic campaign names, never names, emails or other personal identifiers. Source labels are client reports, not proof of causality.</p>
      <form className="mt-5" onSubmit={async (e) => { e.preventDefault(); const signature = JSON.stringify({ channel, label }); if (attempt.current?.signature !== signature) attempt.current = { signature, id: crypto.randomUUID() }; if (await mutate("post", "sources", { channel, label, requestId: attempt.current.id }, "Source link saved.")) { setLabel(""); attempt.current = null; } }}><fieldset className="grid min-w-0 gap-4 sm:grid-cols-2" disabled={busy || data.sources.length >= 20}><label className="block text-sm font-semibold">Source channel<select aria-label="Source channel" className="input-field mt-2" value={channel} onChange={(e) => setChannel(e.target.value)}>{["website", "social", "search", "referral", "email", "print", "other"].map((s) => <option key={s} value={s}>{s}</option>)}</select></label><label className="block text-sm font-semibold">Generic campaign label<input className="input-field mt-2" pattern={"[a-z][a-z0-9\\-]{0,39}"} required maxLength={40} value={label} onChange={(e) => setLabel(e.target.value)} /></label></fieldset><button className="btn-secondary mt-4" disabled={busy || data.sources.length >= 20}>Create source link</button></form>
      {!data.sources.length && <p className="mt-5 text-sm text-muted">No source links have been created.</p>}<div className="mt-5 space-y-4">{data.report.rows.map((row) => <article className="rounded-xl border border-slate-200 p-4 dark:border-slate-700" key={row.id}><h3 className="break-words font-semibold">{row.label}</h3><p className="mt-2 text-sm leading-6">Views {row.visits} · free enrollments {row.freeEnrollments} · live paid enrollments {row.livePaidEnrollments} · live recorded receipts {formatInr(row.receiptsMinor)}</p>{row.id !== "unknown" && <><p className="mt-2 text-xs text-muted">{row.channel} · {row.active ? "Active" : "Inactive; earlier attribution retained"}</p><label className="mt-3 block text-sm">Copyable source URL<input className="input-field mt-2 text-xs" readOnly value={`${window.location.origin}/catalog/${encodeURIComponent(data.course.slug)}?source=${row.code}`} onFocus={(e) => e.target.select()} /></label><button className="btn-secondary mt-3" disabled={busy} onClick={() => mutate("put", `sources/${row.id}`, { active: !row.active, version: row.version }, "Source link updated.")}>{row.active ? "Deactivate source" : "Reactivate source"}</button></>}</article>)}</div></section>
    <section className="card mt-5"><h2 className="text-xl font-semibold">Private interest requests</h2><p className="mt-3 text-sm leading-7 text-muted">Only this course’s owner and admins can view contacts. Status changes send no messages. Permission to respond is separate from ongoing marketing consent. Contacts expire; erase an entry when no longer needed.</p><p className="mt-3 text-sm">Pending {data.report.interest.pending} · contacted {data.report.interest.contacted} · closed {data.report.interest.closed}</p>
      {!data.interest.requests.length && <p className="mt-5 text-sm text-muted">{data.interest.total ? "No requests on this page. Go to the previous page." : "No retained interest requests."}</p>}<div className="mt-5 space-y-4">{data.interest.requests.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><h3 className="break-all font-semibold">{item.email}</h3><p className="mt-2 text-sm">{item.purpose === "demo" ? "Demo information" : "Course information"} · {item.status}</p><p className="mt-2 text-sm">Ongoing marketing consent: {item.marketingConsent ? `given ${new Date(item.marketingConsentAt).toLocaleDateString()}` : "not given"}.</p><p className="mt-2 text-xs text-muted">Requested {new Date(item.createdAt).toLocaleDateString()} · expires {new Date(item.expiresAt).toLocaleDateString()}</p><label className="mt-3 block text-sm">Request status<select aria-label="Request status" className="input-field mt-2" disabled={busy} value={item.status} onChange={(e) => mutate("put", `interest/${item.id}`, { status: e.target.value, version: item.version }, "Request status saved. No message was sent.")}>{["pending", "contacted", "closed"].map((s) => <option key={s} value={s}>{s}</option>)}</select></label><button className="btn-danger mt-3" disabled={busy} onClick={async () => { if (await decide({ title: "Erase this contact request?", body: "Permanently remove this email and request. This cannot be undone.", confirmLabel: "Erase request", destructive: true })) mutate("delete", `interest/${item.id}`, { version: item.version }, "Contact request erased."); }}>Erase request</button></article>)}</div><div className="mt-5 flex flex-wrap items-center gap-3"><button className="btn-secondary" disabled={busy || page <= 1} onClick={() => setPage(page - 1)}>Previous requests</button><span className="text-sm">Page {data.interest.page} · {data.interest.total} retained requests</span><button className="btn-secondary" disabled={busy || page * 20 >= data.interest.total} onClick={() => setPage(page + 1)}>Next requests</button></div>
    </section></section>;
}
