import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useSelector } from "react-redux";
import { BookOpen, CheckCircle2, Globe2, GraduationCap, Play, UserRound, ArrowRight } from "lucide-react";
import axiosInstance, { errorMessage } from "../../services/axiosInstance.js";
import PrivateVideoPlayer from "../../components/PrivateVideoPlayer.jsx";
import LoadingSkeleton from "../../components/LoadingSkeleton.jsx";
import CourseNotes from "../../components/CourseNotes.jsx";
import CourseArtwork from "../../components/CourseArtwork.jsx";
import { getCourse } from "../../services/courseService.js";
import CoursePayment from "../../components/CoursePayment.jsx";
export default function CourseDetailsPage() {
  const { id } = useParams(), user = useSelector((state) => state.auth.user);
  const [data, setData] = useState(null), [selected, setSelected] = useState(null), [error, setError] = useState(""), [playError, setPlayError] = useState(""), [progress, setProgress] = useState({ completedLessons: [] }), [saving, setSaving] = useState(false);
  const content = useRef(null), pending = useRef(false);
  const [paymentCourseId, setPaymentCourseId] = useState(null);
  const load = useCallback(async () => {
    try {
      const result = await getCourse(id);
      const saved = user.role === "student" && result.access?.videos !== false ? (await axiosInstance.get(`/courses/${result.course._id}/progress`)).data.data.progress : { completedLessons: [] };
      const lessons = result.modules.flatMap((module) => module.lessons);
      setData(result); setProgress(saved); setError(""); setPaymentCourseId(null);
      setSelected((current) => lessons.some((lesson) => lesson._id === current) ? current : lessons.find((lesson) => !saved.completedLessons.includes(lesson._id))?._id || lessons[0]?._id || null);
    } catch (e) { setData(null); if (e.response?.data?.code === "PAYMENT_REQUIRED") { setPaymentCourseId(e.response.data.courseId || id); setError(""); } else { setPaymentCourseId(null); setError(errorMessage(e)); } }
  }, [id, user.role]);
  useEffect(() => { load(); const timer = setInterval(load, 15000); return () => clearInterval(timer); }, [load]);
  const lessons = data?.modules.flatMap((module) => module.lessons) || [], lesson = lessons.find((item) => item._id === selected), videosOpen = data?.access?.videos !== false, ready = videosOpen && lesson?.video?.status === "ready";
  const next = lessons.find((item) => item._id !== selected && !progress.completedLessons.includes(item._id));
  const focusContent = () => { content.current?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth", block: "start" }); content.current?.focus({ preventScroll: true }); };
  const markComplete = async () => { if (pending.current) return; pending.current = true; setSaving(true); try { setProgress((await axiosInstance.post(`/lessons/${lesson._id}/complete`)).data.data.progress); setPlayError(""); } catch (e) { setPlayError(errorMessage(e)); } finally { pending.current = false; setSaving(false); } };
  return <section><Link className="text-sm text-primary-600 dark:text-primary-300" to="/dashboard">← Dashboard</Link>{paymentCourseId && <CoursePayment key={paymentCourseId} courseId={paymentCourseId} onAccess={load} />}{error && <div className="card mt-5" role="alert"><p className="text-red-700 dark:text-red-300">{error}</p><button className="btn-secondary mt-4" onClick={load}>Retry course</button></div>}{!data ? !error && !paymentCourseId && <LoadingSkeleton variant="detail" label="Loading course…" /> : <>
    <header className="card course-overview mt-5 !p-6 sm:!p-8"><div className="min-w-0"><p className="eyebrow">{data.course.category?.name || "Your course"}</p><h1 className="mt-3 break-words text-3xl font-semibold sm:text-4xl">{data.course.title}</h1><p className="mt-4 line-clamp-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{data.course.description}</p><div className="course-meta mt-5">{data.course.instructor?.name && <span><UserRound size={15} />{data.course.instructor.name}</span>}<span className="capitalize"><GraduationCap size={15} />{data.course.level || "beginner"}</span><span><Globe2 size={15} />{data.course.language || "English"}</span><span><BookOpen size={15} />{lessons.length} available {lessons.length === 1 ? "lesson" : "lessons"}</span></div><div className="mt-6 flex flex-wrap items-center gap-3">{!videosOpen || lessons.length > 0 ? <button className="btn-primary gap-2" onClick={focusContent}><Play size={16} />{!videosOpen ? "View course outline" : user.role !== "student" ? "Preview lessons" : progress.percentage === 100 ? "Review course" : progress.completedLessons.length ? "Continue learning" : "Start learning"}</button> : <a className="btn-primary" href="#course-notes-title">Explore course notes</a>}<span className="text-xs text-slate-500 dark:text-slate-400">{!videosOpen ? "Videos unlock after this instructor gives you access" : user.role === "student" ? "Available to your assigned account" : "Instructor preview"}</span></div>{user.role === "student" && videosOpen && lessons.length > 0 && <div className="mt-5 max-w-sm"><div className="mb-2 flex justify-between text-xs text-slate-500 dark:text-slate-400"><span>Your lesson progress</span><span>{progress.percentage || 0}% complete</span></div><progress className="course-progress" aria-label="Course completion" value={progress.percentage || 0} max={100} /></div>}</div><CourseArtwork course={data.course} className="aspect-[4/3] rounded-xl" /></header>
    <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]"><section ref={content} tabIndex={-1} className="card course-content-panel min-w-0"><p className="eyebrow">{lesson ? "Your lesson" : "Learning materials"}</p><h2 className="mb-5 mt-2 text-xl font-semibold">{lesson?.title || "Course materials"}</h2>
      {!videosOpen && <div className="rounded-xl border border-slate-200 p-5 text-sm leading-6 dark:border-slate-600" role="status">You can see this course because it is published. {data.course.instructor?.name || "The instructor"} has not given your account access, so its videos, lesson text, and PDF notes stay locked.</div>}
      {ready && <PrivateVideoPlayer key={lesson._id} lessonId={lesson._id} title={lesson.title} studentId={user.role === "student" ? user.id : undefined} />}
      {videosOpen && lesson?.contentType === "video" && !ready && <div className="rounded-xl border border-slate-200 p-5 text-sm leading-6 dark:border-slate-600" role="status">{lesson.video?.status === "verifying" ? "The uploaded MP4 is being checked. This page will update when it is ready." : lesson.video?.status === "failed" ? "The upload could not be verified. Your instructor can check the upload or replace it with a valid MP4." : lesson.video?.status === "queued" ? "This older upload is queued for server processing. Your instructor may need to replace it with a preconverted MP4." : lesson.video?.status === "processing" ? "This older upload is being processed." : "The instructor has not finished uploading this lesson’s video yet."}</div>}
      {videosOpen && lesson?.contentType === "text" && <div className="rounded-xl border border-slate-200 bg-slate-50 p-5 text-sm leading-7 whitespace-pre-wrap dark:border-slate-600 dark:bg-[#132224]">{lesson.content}</div>}
      {!lesson && <p className="text-sm leading-6 text-slate-500 dark:text-slate-400">The PDF handouts for this course are below. Your instructor can add lessons here as the course develops.</p>}
      {playError && <div className="mt-4" role="alert"><p className="text-red-700 dark:text-red-300">{playError}</p><button className="btn-secondary mt-3" onClick={async () => { await load(); setPlayError(""); }}>Retry playback</button></div>}
      {videosOpen && user.role === "student" && lesson && (ready || lesson.contentType === "text") && <div className="mt-5 flex flex-wrap gap-3"><button disabled={saving || progress.completedLessons.includes(lesson._id)} className="btn-primary gap-2" onClick={markComplete}>{progress.completedLessons.includes(lesson._id) && <CheckCircle2 size={16} />}{progress.completedLessons.includes(lesson._id) ? "Lesson completed" : saving ? "Saving…" : "Mark lesson complete"}</button>{progress.completedLessons.includes(lesson._id) && next && <button className="btn-secondary gap-2" onClick={() => { setSelected(next._id); setPlayError(""); }}>Next lesson<ArrowRight size={16} /></button>}</div>}
      {ready && <p className="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">Use the player controls for playback speed, volume, seeking, and full screen.</p>}
    </section><nav className="card course-outline h-fit" aria-label="Course lessons"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">Lesson outline</h2><span className="text-xs text-slate-500 dark:text-slate-400">{lessons.length} lessons</span></div>{!lessons.length && <p className="mt-4 text-sm leading-6 text-slate-500 dark:text-slate-400">Course notes are available below. There are no available lessons yet.</p>}{data.modules.filter((module) => module.lessons.length).map((module) => <div className="mt-5" key={module._id}><h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400">{module.title}</h3><ul className="space-y-1">{module.lessons.map((item, index) => <li key={item._id}><button aria-current={selected === item._id ? "true" : undefined} onClick={() => { setSelected(item._id); setPlayError(""); }}>{progress.completedLessons.includes(item._id) ? <CheckCircle2 size={16} className="shrink-0 text-primary-600 dark:text-primary-300" /> : <span className="shrink-0 text-xs tabular-nums">{String(index + 1).padStart(2, "0")}</span>}<span className="break-words">{item.title}</span></button></li>)}</ul></div>)}</nav></div>
    <section className="card mt-7"><p className="eyebrow">About this course</p><h2 className="mt-2 text-xl font-semibold">Course overview</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-600 dark:text-slate-300">{data.course.description}</p><div className="mt-5 grid gap-6 sm:grid-cols-2">{data.course.learningOutcomes?.length > 0 && <div><h3 className="font-semibold">What you will learn</h3><ul className="mt-3 space-y-3">{data.course.learningOutcomes.map((item, index) => <li key={index} className="flex gap-2 text-sm leading-6 text-slate-600 dark:text-slate-300"><CheckCircle2 className="mt-1 shrink-0 text-primary-600 dark:text-primary-300" size={16} />{item}</li>)}</ul></div>}{data.course.requirements?.length > 0 && <div><h3 className="font-semibold">Before you begin</h3><ul className="mt-3 list-inside list-disc space-y-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{data.course.requirements.map((item, index) => <li key={index}>{item}</li>)}</ul></div>}</div>{data.course.instructor?.bio && <div className="mt-6 border-t border-slate-100 pt-5 dark:border-slate-700"><h3 className="font-semibold">Meet {data.course.instructor.name}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-600 dark:text-slate-300">{data.course.instructor.bio}</p></div>}</section>
    {videosOpen && <CourseNotes courseId={data.course._id} />}
  </>}</section>;
}
