import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useSelector } from "react-redux";
import axiosInstance, { errorMessage } from "../../services/axiosInstance.js";
import { useDecision } from "../../components/DecisionProvider.jsx";
import WorkspaceIntro from "../../components/WorkspaceIntro.jsx";
const operation = (ref, body) => { const signature = JSON.stringify(body); if (ref.current?.signature !== signature) ref.current = { signature, id: crypto.randomUUID() }; return { ...body, requestId: ref.current.id }; };
function TaskEditor({ task, lessons, courseId, done }) {
  const initial = { title: task?.title || "", instructions: task?.instructions || "", checklist: (task?.checklist || []).join("\n"), lesson: task?.lessonId || "", active: task?.active ?? true };
  const [form, setForm] = useState(initial), [busy, setBusy] = useState(false), [error, setError] = useState(""); const pending = useRef(false), baseline = useRef(JSON.stringify(initial)), decide = useDecision();
  const cancel = async () => { if (JSON.stringify(form) !== baseline.current && !await decide({ title: "Discard unsaved task changes?", body: "Saved instructions and student records are retained. These unsaved edits will be discarded.", confirmLabel: "Discard changes", destructive: true })) return; done(); };
  return <form className="card mt-5" onSubmit={async (e) => { e.preventDefault(); if (pending.current) return; pending.current = true; setBusy(true); setError(""); try { await axiosInstance({ method: task ? "put" : "post", url: `/courses/${courseId}/practicals${task ? `/${task.id}` : ""}`, data: { ...form, lesson: form.lesson || null, checklist: form.checklist.split("\n").map((s) => s.trim()).filter(Boolean), ...(task ? { version: task.version } : {}) } }); done(true); } catch (err) { setError(errorMessage(err)); } finally { pending.current = false; setBusy(false); } }}>
    <h2 className="text-xl font-semibold">{task ? "Edit practical task" : "Author a practical task"}</h2><fieldset disabled={busy} className="mt-5 min-w-0 space-y-5">
      <label className="block text-sm font-semibold">Task title<input className="input-field mt-2" required maxLength={160} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label>
      <label className="block text-sm font-semibold">Task instructions<textarea aria-label="Task instructions" className="input-field mt-2" required maxLength={5000} rows={5} value={form.instructions} onChange={(e) => setForm({ ...form, instructions: e.target.value })} /></label>
      <label className="block text-sm font-semibold">Related lesson (optional)<select aria-label="Related lesson (optional)" className="input-field mt-2" value={form.lesson} onChange={(e) => setForm({ ...form, lesson: e.target.value })}><option value="">Whole course</option>{lessons.map((l) => <option key={l._id} value={l._id}>{l.title}</option>)}</select></label>
      <label className="block text-sm font-semibold">Checklist (one item per line)<textarea aria-label="Checklist (one item per line)" className="input-field mt-2" maxLength={4200} rows={4} value={form.checklist} onChange={(e) => setForm({ ...form, checklist: e.target.value })} /><span className="mt-2 block text-sm font-normal text-muted">Optional: up to 20 items, 200 characters each.</span></label>
      <label className="flex min-h-12 items-center gap-3 text-sm"><input type="checkbox" checked={form.active} onChange={(e) => setForm({ ...form, active: e.target.checked })} />Available to entitled students</label>
    </fieldset>{error && <p role="alert" className="mt-4 text-red-700 dark:text-red-300">{error}</p>}<div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} className="btn-primary">{busy ? "Saving…" : "Save task"}</button><button disabled={busy} className="btn-secondary" type="button" onClick={cancel}>Cancel</button></div><p className="mt-4 text-sm leading-7 text-muted">Changes create a new task version. Student completion remains self-reported, separate from lesson completion and assessment scores.</p>
  </form>;
}
function PracticalRecorder({ task, changed }) {
  const current = task.record?.taskVersion === task.version ? task.record : null;
  const [response, setResponse] = useState(current?.response || ""), [checked, setChecked] = useState(current?.checked || task.checklist.map(() => false)), [completed, setCompleted] = useState(Boolean(current?.completed)), [busy, setBusy] = useState(false), [error, setError] = useState(""); const pending = useRef(false), op = useRef(null);
  return <form className="mt-5" onSubmit={async (e) => { e.preventDefault(); if (pending.current) return; pending.current = true; setBusy(true); setError(""); try { await axiosInstance.post(`/practicals/${task.id}/record`, operation(op, { taskVersion: task.version, revision: current?.revision || 0, response, checked, completed })); await changed(); } catch (err) { setError(errorMessage(err)); } finally { pending.current = false; setBusy(false); } }}><fieldset disabled={busy} className="min-w-0 space-y-4">
    {task.checklist.map((item, i) => <label className="flex min-h-12 items-start gap-3 rounded-xl border border-line p-3 text-sm leading-7" key={i}><input className="mt-1.5" type="checkbox" checked={checked[i]} onChange={(e) => setChecked(checked.map((v, n) => n === i ? e.target.checked : v))} /><span className="min-w-0 break-words">{item}</span></label>)}
    <label className="block text-sm font-semibold">Your text response (optional)<textarea aria-label="Your text response (optional)" className="input-field mt-2" rows={4} maxLength={3000} value={response} onChange={(e) => setResponse(e.target.value)} /></label><label className="flex min-h-12 items-start gap-3 text-sm leading-7"><input className="mt-1.5" type="checkbox" checked={completed} onChange={(e) => setCompleted(e.target.checked)} /><span>I completed this task myself (self-reported)</span></label>
    <p className="text-sm leading-7 text-muted">Your course owner/admin can read this response. This is an ungraded self-report; it does not certify competence or complete a lesson.</p>
  </fieldset>{error && <p role="alert" className="mt-4 text-red-700 dark:text-red-300">{error}</p>}<button className="btn-primary mt-4" disabled={busy}>{busy ? "Saving…" : "Save practical record"}</button>{current && <p role="status" className="mt-3 text-sm">{current.completed ? "Self-reported complete" : current.response ? "Text response saved" : "Checklist progress saved"}</p>}{task.record && !current && <p className="mt-3 text-sm text-muted">A record from version {task.record.taskVersion} is retained. These updated instructions need a new record.</p>}</form>;
}
function QuestionComposer({ lessons, courseId, saved, cancel }) {
  const [text, setText] = useState(""), [lesson, setLesson] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""); const op = useRef(null), pending = useRef(false), decide = useDecision();
  return <form className="card mt-5" onSubmit={async (e) => { e.preventDefault(); if (pending.current) return; pending.current = true; setBusy(true); setError(""); try { await axiosInstance.post(`/courses/${courseId}/questions`, operation(op, { text, lesson: lesson || null })); saved(); } catch (err) { setError(errorMessage(err)); } finally { pending.current = false; setBusy(false); } }}><fieldset disabled={busy} className="min-w-0 space-y-4"><legend className="text-xl font-semibold">Ask a private course question</legend><label className="mt-4 block text-sm font-semibold">Your question<textarea aria-label="Your question" className="input-field mt-2" required maxLength={2000} rows={5} value={text} onChange={(e) => setText(e.target.value)} /></label><label className="block text-sm font-semibold">Question lesson (optional)<select aria-label="Question lesson (optional)" className="input-field mt-2" value={lesson} onChange={(e) => setLesson(e.target.value)}><option value="">Whole course</option>{lessons.map((l) => <option key={l._id} value={l._id}>{l.title}</option>)}</select></label><p className="text-sm leading-7 text-muted">Visible to you and the course owner/admin. Other students cannot read this thread. Up to 50 retained threads per course and 10 question requests per hour.</p></fieldset>{error && <p className="mt-4 text-red-700 dark:text-red-300" role="alert">{error}</p>}<div className="mt-5 flex flex-wrap gap-3"><button className="btn-primary" disabled={busy}>{busy ? "Saving…" : "Send question"}</button><button className="btn-secondary" type="button" disabled={busy} onClick={async () => { if (!text && !lesson || await decide({ title: "Discard this unsent question?", body: "It has not been sent to your instructor.", confirmLabel: "Discard question", destructive: true })) cancel(); }}>Cancel</button></div></form>;
}
function QuestionThread({ question, owner, changed }) {
  const [reply, setReply] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""); const op = useRef(null), pending = useRef(false), decide = useDecision();
  const save = async (status) => { if (pending.current) return; pending.current = true; setBusy(true); setError(""); try { if (owner) await axiosInstance.post(`/course-questions/${question.id}/replies`, operation(op, { text: reply, version: question.version })); else await axiosInstance.put(`/course-questions/${question.id}/status`, { resolved: status, version: question.version }); await changed(); } catch (e) { setError(errorMessage(e)); throw e; } finally { pending.current = false; setBusy(false); } };
  return <article className="card mt-5 min-w-0"><p className="eyebrow">{question.status}{owner && question.studentName ? ` · ${question.studentName}` : ""}</p><h3 className="mt-3 whitespace-pre-wrap break-words text-lg font-semibold">{question.text}</h3><p className="mt-2 text-xs text-muted">Asked {new Date(question.createdAt).toLocaleString()}</p><ol className="mt-4 space-y-3">{question.replies.map((r, i) => <li className="rounded-xl border border-line p-4" key={i}><p className="text-sm font-semibold">{r.name}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7">{r.text}</p></li>)}</ol>
    {owner && question.status !== "resolved" && question.replies.length < 10 && <form className="mt-5" onSubmit={(e) => { e.preventDefault(); save().catch(() => {}); }}><label className="block text-sm font-semibold">Reply to this question<textarea aria-label="Reply to this question" className="input-field mt-2" rows={4} required maxLength={2000} disabled={busy} value={reply} onChange={(e) => setReply(e.target.value)} /></label><button className="btn-primary mt-4" disabled={busy}>{busy ? "Saving…" : "Send reply"}</button></form>}
    {!owner && <button className="btn-secondary mt-5" disabled={busy} onClick={() => decide({ title: question.status === "resolved" ? "Reopen this question?" : "Mark this question resolved?", body: question.status === "resolved" ? "Your course owner/admin will see it as an open thread again." : "You can reopen it later. This does not change course completion.", confirmLabel: question.status === "resolved" ? "Reopen question" : "Mark resolved", onConfirm: () => save(question.status !== "resolved") })}>{question.status === "resolved" ? "Reopen question" : "Mark resolved"}</button>}
    {error && <p role="alert" className="mt-4 text-red-700 dark:text-red-300">{error}</p>}
  </article>;
}
function Pages({ page, total, setPage, label }) { return <nav aria-label={label} className="mt-5 flex flex-wrap items-center gap-3"><button className="btn-secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous {label}</button><span>Page {page}</span><button className="btn-secondary" disabled={page * 20 >= total} onClick={() => setPage(page + 1)}>Next {label}</button></nav>; }
export default function LearningSupportPage() {
  const { id } = useParams(), owner = useSelector((s) => s.auth.user?.role !== "student");
  const [data, setData] = useState(null), [error, setError] = useState(""), [editing, setEditing] = useState(null), [asking, setAsking] = useState(false), [qpage, setQpage] = useState(1), [rpage, setRpage] = useState(1), [notice, setNotice] = useState("");
  const load = useCallback(async (signal) => { try { const results = await Promise.all([axiosInstance.get(owner ? `/courses/mine/${id}` : `/courses/${id}`, { signal }), axiosInstance.get(`/courses/${id}/practicals`, { signal }), axiosInstance.get(`/courses/${id}/questions`, { params: { page: qpage }, signal }), ...(owner ? [axiosInstance.get(`/courses/${id}/practical-records`, { params: { page: rpage }, signal })] : [])]); if (signal?.aborted) return; setData({ ...results[0].data.data, tasks: results[1].data.data.tasks, questions: results[2].data.data, records: results[3]?.data.data }); setError(""); } catch (e) { if (e.code !== "ERR_CANCELED") { setData(null); setError(errorMessage(e)); } } }, [id, owner, qpage, rpage]);
  useEffect(() => { const controller = new AbortController(); load(controller.signal); return () => controller.abort(); }, [load]);
  const lessons = data?.modules.flatMap((m) => m.lessons) || [];
  return <section><Link className="text-sm text-primary-700 underline dark:text-primary-300" to={owner ? `/instructor/courses/${id}/curriculum` : `/courses/${id}`}>← {owner ? "Course curriculum" : "Course"}</Link><div className="mt-5"><WorkspaceIntro eyebrow="Practice karein, sawaal poochein" title="Practice and course questions">{data?.course.title || "Your course learning support"}</WorkspaceIntro></div>{error && <div role="alert" className="card mt-5"><p className="text-red-700 dark:text-red-300">{error}</p><button className="btn-secondary mt-4" onClick={() => load()}>Reload support</button></div>}{!data && !error && <p role="status" className="mt-5">Loading learning support…</p>}{notice && <p className="mt-4" role="status">{notice}</p>}
    {data && <><section className="mt-7"><h2 className="text-2xl font-semibold">Practical tasks</h2>{owner && editing === null && <button className="btn-primary mt-4" disabled={data.tasks.length >= 40} onClick={() => setEditing("new")}>Create practical task</button>}{owner && editing !== null ? <TaskEditor key={editing === "new" ? "new" : `${editing.id}:${editing.version}`} task={editing === "new" ? null : editing} lessons={lessons} courseId={id} done={async (saved) => { setEditing(null); if (saved) { setNotice("Practical task saved."); await load(); } }} /> : <>{!data.tasks.length && <p className="card mt-5">No practical tasks have been authored yet.</p>}{data.tasks.map((task) => <article className="card mt-5 min-w-0" key={task.id}><p className="eyebrow">Version {task.version}{!task.active && " · Hidden from students"}</p><h3 className="mt-3 break-words text-xl font-semibold">{task.title}</h3><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-7">{task.instructions}</p>{owner ? <><ul className="mt-4 list-inside list-disc space-y-2 text-sm">{task.checklist.map((v, i) => <li key={i}>{v}</li>)}</ul><button className="btn-secondary mt-5" onClick={() => setEditing(task)}>Edit task</button></> : <PracticalRecorder key={`${task.id}:${task.version}:${task.record?.revision || 0}`} task={task} changed={load} />}</article>)}</>}</section>
      {owner && <section className="mt-7"><h2 className="text-2xl font-semibold">Private practical responses</h2>{!data.records.records.length && <p className="card mt-5">No student records yet.</p>}{data.records.records.map((r) => <article className="card mt-5" key={r.id}><h3 className="break-words text-lg font-semibold">{r.taskTitle}</h3><p className="mt-2 text-sm text-muted">{r.studentName || "Student"} · Version {r.taskVersion} · {r.completed ? "Self-reported complete" : r.response ? "Text response saved" : "Checklist progress saved"}</p><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-7">{r.response || "No text response."}</p></article>)}<Pages page={rpage} total={data.records.total} setPage={setRpage} label="response pages" /></section>}
      <section className="mt-7"><h2 className="text-2xl font-semibold">{owner ? "Private student questions" : "Your private questions"}</h2>{!owner && !asking && <button className="btn-primary mt-4" disabled={data.questions.total >= 50} onClick={() => setAsking(true)}>Ask a course question</button>}{!owner && asking && <QuestionComposer lessons={lessons} courseId={id} cancel={() => setAsking(false)} saved={async () => { setAsking(false); setNotice("Your question was saved privately."); await load(); }} />}{!data.questions.questions.length && <p className="card mt-5">No question threads yet.</p>}{data.questions.questions.map((q) => <QuestionThread key={`${q.id}:${q.version}`} question={q} owner={owner} changed={load} />)}<Pages page={qpage} total={data.questions.total} setPage={setQpage} label="question pages" /></section>
    </>}
  </section>;
}
